/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ccsfrzzwmjejsxavojrs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc2Zyenp3bWplanN4YXZvanJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MzMxMjYsImV4cCI6MjA4NTUwOTEyNn0.K8QXFq-dTH3O3sbOUCV7dpfuEbzumu71baM-C8W42sI"